version: '3'
services:
  web:
    build: .
    depends_on:
      - 'mysqlDb'
    # entrypoint: "./wait-for-it.sh mysqlDb:3306"
    ports:
      - "3000:3000"
    # command: ["./wait-for-it.sh", "mysqlDb", "--", "npm", "start"]
  mysqlDb:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - 'MYSQL_ROOT_PASSWORD=1472580369'
      - 'MYSQL_DATABASE=blog'
      - 'MYSQL_USER=blogAdmin'
      - 'MYSQL_PASSWORD=blogadmin'
